#!/bin/sh
#
#  Install
###########################################################################
#
#  Purpose:  This script invokes the Ant utility to perform the build for
#            this product.
#
#  Usage:  Install
#
###########################################################################

cd `dirname $0`

. ./Configuration

mkdir -p ${LOG_DIR}

if [ ! -e "${MAVEN_REPO_LOCAL}" ] ; then
  echo "MAVEN_REPO_LOCAL is not defined or does not exist."
  exit 1
fi
mvn -Dmaven.repo.local=${MAVEN_REPO_LOCAL} clean package
