#!/bin/sh

cd `dirname $0`; . Configuration

if [ $# -ne 2 ]
then
    echo "Usage: $0 Solr_Path Solr_Port"
    exit 1
fi

export SOLR_INDEX_PATH=$1
export SOLR_PORT=$2

export SOLR_LOGS_DIR=${SOLR_INDEX_PATH}/logs

${SOLR} start -s ${SOLR_INDEX_PATH} -p ${SOLR_PORT}
